# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 2040 - Richmond Squadron
email: 2040@aircadets.org
description: >- # this means to ignore newlines until "baseurl:"
  2040 Richmond Squadron is based in Richmond North Yorkshire. We do a multitude
   of activities from flying to hiking to first aid training and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://2040richmondsquadron.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  johnathan99j

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Team names, titles and social links
people:
  - name: Andy Ayre
    pic: blank
    position: Commanding Officer

  - name: Peter Godwin
    pic: blank
    position: Civilian Instructor

  - name: Abigail Swift
    pic: blank
    position: Sergeant

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/
  - title: envelope
    url: mailto:2040@aircadets.org
  - title: facebook
    url: https://www.facebook.com/richmondaircadets/

# Build settings
markdown: kramdown
permalink: pretty
