version: '3'
services:
  2040_dev_server:
    image: jekyll/jekyll:latest
    command: bundle install
    command: jekyll serve --watch --force_polling
    ports:
     - "4000:4000"
    volumes:
     - ./:/srv/jekyll
